version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "abdulsagheer"
    assignees:
      - "abdulsagheer"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "black"
        update-types: ["version-update:semver-major"]
      - dependency-name: "flake8"
        update-types: ["version-update:semver-major"]
      - dependency-name: "mypy"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "abdulsagheer"
    assignees:
      - "abdulsagheer"
    labels:
      - "dependencies"
      - "github-actions" 